-- 닉네임, 작성한 게시글 갯수 출력
SELECT NICKNAME, COUNT(*) 
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.USERID, NICKNAME;

-- 1) 각 게시글의 제목, 댓글 개수 출력
-- + 게시글에 댓글이 없는 경우 개수를 0으로 출력

SELECT TITLE, COUNT(COMMENTNO) AS 댓글개수
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO, TITLE;

-- 게시글 번호, 게시글 제목, 내용, 작성일, 작성자 닉네임,  댓글 개수(없으면0) 출력
SELECT B.BOARDNO, TITLE, B.CONTENTS, B.CDATETIME, B.USERID, COUNT(COMMENTNO) AS 댓글개수
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO, TITLE, B.CONTENTS, B.CDATETIME, B.USERID;


SELECT B.BOARDNO, TITLE, B.CONTENTS, B.CDATETIME, NICKNAME, COMMENT_CNT
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
INNER JOIN (
    SELECT B.BOARDNO, COUNT(COMMENTNO) AS COMMENT_CNT
    FROM TBL_BOARD B
    LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
    GROUP BY B.BOARDNO
) T ON B.BOARDNO = T.BOARDNO;


---
-- CASE ~ WHEN
-- PROFESSOR
-- 1. PROFESSOR 테이블에서 400이상의 급여를 받으면 A, 
--		300~400 사이면 B, 나머지는 C로 출력
--    교수이름, 급여 등급(A~C)

SELECT 
    NAME,
    CASE 
        WHEN PAY >= 400 THEN 'A'
        WHEN PAY >= 300 THEN 'B'
        ELSE 'C'
    END AS PAY_GRADE
FROM PROFESSOR;






