SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;

SELECT TITLE, CONTENTS, NICKNAME, B.USERID 
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
ORDER BY BOARDNO;


-- 각 유저가 작성한 게시글의 수(출력 컬럼 : 유저 아이디, 이름, 게시글 개수)
-- LEFT
SELECT U.USERID, NAME, COUNT(BOARDNO) AS CNT
FROM TBL_USER U
LEFT JOIN TBL_BOARD B ON B.USERID = U.USERID
GROUP BY U.USERID, NAME;

-- RIGHT
SELECT U.USERID, NAME, COUNT(BOARDNO) AS CNT
FROM TBL_BOARD B
RIGHT JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY U.USERID, NAME;

-- 각 유저가 작성한 댓글의 수(출력 컬럼 : 유저 아이디, 이름, 댓글 개수)
SELECT U.USERID, NAME, COUNT(COMMENTNO) AS CNT
FROM TBL_USER U
LEFT JOIN TBL_COMMENT C ON U.USERID = C.USERID
GROUP BY U.USERID, NAME;


