-- TBL_USER, TBL_BOARD, TBL_COMMENT
--1. 아이디에 user가 들어가는 사람이 작성한 게시글의 수를 구하시오.
SELECT COUNT(*)
FROM TBL_BOARD
WHERE USERID LIKE '%user%';
--2. USER의 핸드폰 번호 가운데를 *로 처리하시오.
--(ex, 010-****-5678) -- '가운데 숫자는 4글자 고정'
SELECT SUBSTR(PHONE, 1, INSTR(PHONE, '-')) || '****' || SUBSTR(PHONE, INSTR(PHONE, '-')+5, LENGTH(PHONE)) PHONE
FROM TBL_USER;

--SELECT REPLACE(PHONE, SUBSTR(PHONE, 5, 4), '****'), SUBSTR(PHONE, 5, 4)
--FROM TBL_USER;
--SELECT *
--FROM TBL_USER;

--3. 게시글에 좋아요 개수가 가장 큰 게시글을 작성한 사람의 아이디, 이름, 좋아요개수를 출력하시오.
SELECT U.USERID, NAME, FAVORITE
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
WHERE FAVORITE = (
    SELECT MAX(FAVORITE)
    FROM TBL_BOARD
);

--4. 게시글 번호, 제목, 내용, 작성자 닉네임, 댓글 수(없으면 0)를 출력하시오.
SELECT B.BOARDNO, TITLE, B.CONTENTS, NICKNAME, COUNT(COMMENTNO) AS 댓글개수
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO, TITLE, B.CONTENTS, NICKNAME;


--5. 조회수가 가장 큰 게시글의 게시글 번호, 제목, 작성자 닉네임을 출력하시오.
SELECT BOARDNO, TITLE, NICKNAME
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
WHERE CNT = (
    SELECT MAX(CNT)
    FROM TBL_BOARD
);





