-- 사용자 정의 함수
CREATE OR REPLACE FUNCTION REVIEW1(P_NUMBER IN NUMBER)
RETURN NUMBER
IS
BEGIN
    RETURN P_NUMBER * 10;
END;
/

SELECT ENAME, SAL, REVIEW1(SAL), REVIEW1(10)
FROM EMP;

-- 프로시저
SELECT * FROM PROFESSOR;
CREATE OR REPLACE PROCEDURE REVIEW2
    (
        P_PROFNO IN PROFESSOR.PROFNO%TYPE,
        P_BONUS IN PROFESSOR.BONUS%TYPE
    )
IS
    P_COUNT NUMBER;
BEGIN
    UPDATE PROFESSOR
    SET
        BONUS = NVL(BONUS, 0) + P_BONUS
    WHERE PROFNO = P_PROFNO;
    P_COUNT := SQL%ROWCOUNT;
    IF P_COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('해당 교수번호가 존재하지 않습니다.');
    ELSIF P_COUNT = 1 THEN
        DBMS_OUTPUT.PUT_LINE('정상적으로 수정되었습니다.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('2개이상의 교수 보너스가 수정되었습니다.');
    END IF;
    COMMIT;
END;
/
-- SET SERVEROUTPUT ON;
EXECUTE REVIEW2(1234, 10);

SELECT * FROM STUDENT;

-- 20153075 학번 학생의 키가 1 증가
-- 없는 학번을 입력 후 실행하면 '해당 학생이 없습니다' 출력
-- 키가 업데이트 되었으면 '수정되었습니다' 출력
CREATE OR REPLACE PROCEDURE HEIGHT_UPDATE
    (
        P_STUNO IN STUDENT.STU_NO%TYPE,
        P_HEIGHT IN NUMBER
    )
IS
    P_COUNT NUMBER;
BEGIN
    UPDATE STUDENT
    SET
        STU_HEIGHT = STU_HEIGHT + P_HEIGHT
    WHERE STU_NO = P_STUNO;
    P_COUNT := SQL%ROWCOUNT;
    IF P_COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('해당 학생이 없습니다');
    ELSIF P_COUNT = 1 THEN
        DBMS_OUTPUT.PUT_LINE(P_STUNO || '학번 학생이 수정되었습니다');
    ELSE
        DBMS_OUTPUT.PUT_LINE('여러 학생이 수정되었습니다.');
    END IF;
    COMMIT;
END;
/

EXECUTE HEIGHT_UPDATE(20153075, 1);

CREATE OR REPLACE PROCEDURE STUINFO
    (P_STUNO IN STUDENT.STU_NO%TYPE)
IS
    P_NAME STUDENT.STU_NAME%TYPE;
    P_DEPT STUDENT.STU_DEPT%TYPE;
    P_GRADE STUDENT.STU_GRADE%TYPE;
BEGIN
    SELECT STU_NAME, STU_DEPT, STU_GRADE
    INTO P_NAME, P_DEPT, P_GRADE
    FROM STUDENT
    WHERE STU_NO = P_STUNO;
    
    DBMS_OUTPUT.PUT_LINE('이름 : ' || P_NAME);
    DBMS_OUTPUT.PUT_LINE('학과 : ' || P_DEPT);
    DBMS_OUTPUT.PUT_LINE('학년 : ' || P_GRADE);
END;
/

EXECUTE STUINFO(20153075);










