-- 조인 => 2개 이상의 테이블 연계를 통해 데이터를 추출하는 방법
--    관계형데이터 베이스의 핵심 문법

SELECT * 
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

-- 교수번호, 교수이름, 학과
SELECT PROFNO, NAME, DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO;

-- 사원번호(EMPNO), 이름, 직급(JOB), 부서명(DNAME)
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT EMPNO, ENAME, JOB, DNAME
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

---------
-- 학번, 이름, 학과, 시험점수 출력 (STUDENT, ENROL)
-- + 과목명 (SUBJECT)
SELECT S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE, SUB_NAME
FROM STUDENT S 
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO;

--
SELECT * FROM EMP;
SELECT * FROM SALGRADE;

SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

-- SELF JOIN (자가 조인)

SELECT E1.ENAME, E2.ENAME 매니저이름 
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;
--WHERE E1.ENAME = 'ALLEN';

SELECT * FROM DEPARTMENT;
-- 공과대학에 속한 학과들 출력

SELECT D3.DNAME
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.DEPTNO = D2.PART
INNER JOIN DEPARTMENT D3 ON D2.DEPTNO = D3.PART
WHERE D1.DNAME = '공과대학';




